"""Dixon-Coles fitting: gradient correctness and parameter recovery."""

import math
from datetime import date, timedelta

import numpy as np
import pytest

from bettingedge.config import ModelConfig
from bettingedge.data import synthetic
from bettingedge.data.schema import Match
from bettingedge.models.dixon_coles import DixonColesModel, score_matrix_from_rates


def _toy_matches(n: int = 240, seed: int = 3) -> list[Match]:
    rng = np.random.default_rng(seed)
    teams = [f"T{i}" for i in range(8)]
    start = date(2024, 1, 1)
    matches = []
    for i in range(n):
        home, away = rng.choice(len(teams), size=2, replace=False)
        matches.append(
            Match(
                date=start + timedelta(days=i),
                league="X",
                home=teams[home],
                away=teams[away],
                home_goals=int(rng.poisson(1.5)),
                away_goals=int(rng.poisson(1.1)),
            )
        )
    return matches


def test_analytic_gradient_matches_finite_differences():
    """The hand-derived gradient is what makes backtesting fast — verify it."""
    matches = _toy_matches(120)
    model = DixonColesModel(ModelConfig(half_life_days=200.0, ridge=0.03))

    # Reach into the objective the fitter builds by monkeypatching minimize.
    captured = {}

    import bettingedge.models.dixon_coles as module

    original = module.minimize

    def capture(objective, theta0, **kwargs):
        captured["objective"] = objective
        captured["theta0"] = theta0
        return original(objective, theta0, **kwargs)

    module.minimize = capture
    try:
        model.fit(matches)
    finally:
        module.minimize = original

    objective = captured["objective"]
    rng = np.random.default_rng(11)
    theta = captured["theta0"] + rng.normal(0, 0.2, size=captured["theta0"].shape)
    theta[-1] = -0.05  # keep rho in a sane place

    value, grad = objective(theta)
    step = 1e-6
    for index in rng.choice(theta.size, size=12, replace=False):
        bumped = theta.copy()
        bumped[index] += step
        up, _ = objective(bumped)
        bumped[index] -= 2 * step
        down, _ = objective(bumped)
        numeric = (up - down) / (2 * step)
        assert numeric == pytest.approx(grad[index], abs=2e-5), f"param {index}"


def test_recovers_known_parameters_from_simulated_data():
    """Fit data generated by a known process and check we get the process back."""
    matches, _ = synthetic.generate(seasons=5, seed=21, upcoming_matchdays=1)
    model = DixonColesModel(ModelConfig(half_life_days=400.0, ridge=0.01)).fit(matches)

    assert model.converged
    assert model.home_advantage == pytest.approx(synthetic.TRUE_HOME_ADV, abs=0.10)
    assert model.rho == pytest.approx(synthetic.TRUE_RHO, abs=0.08)
    # Ratings are mean-centred for identifiability.
    assert model.attack.mean() == pytest.approx(0.0, abs=1e-9)
    assert model.defence.mean() == pytest.approx(0.0, abs=1e-9)


def test_stronger_teams_get_higher_ratings():
    """A team that wins everything should top the table."""
    start = date(2024, 1, 1)
    matches = []
    for i in range(120):
        # "Best" hammers everyone; "Worst" loses to everyone.
        matches.append(Match(start + timedelta(days=i), "X", "Best", f"Mid{i % 5}", 4, 0))
        matches.append(Match(start + timedelta(days=i), "X", f"Mid{i % 5}", "Worst", 3, 0))
    model = DixonColesModel(ModelConfig(half_life_days=1000.0)).fit(matches)
    ratings = {r.team: r for r in model.ratings()}
    assert ratings["Best"].attack > ratings["Worst"].attack
    assert ratings["Best"].net > ratings["Worst"].net


def test_unknown_team_falls_back_to_league_average():
    model = DixonColesModel().fit(_toy_matches())
    rating = model.rating("Never Heard Of Them")
    assert (rating.attack, rating.defence, rating.matches) == (0.0, 0.0, 0)
    assert not model.knows("Never Heard Of Them")
    # It must still be priceable rather than blowing up.
    lam, mu = model.expected_goals("Never Heard Of Them", model.teams[0])
    assert lam > 0 and mu > 0


def test_data_confidence_reflects_sample_size():
    model = DixonColesModel().fit(_toy_matches())
    known = model.data_confidence(model.teams[0], model.teams[1])
    unknown = model.data_confidence("Nobody", "Nobody Else")
    assert known > unknown
    assert unknown == 0.0


def test_time_decay_weights_recent_matches_more():
    """Same teams, opposite results — recency should decide the rating order."""
    start = date(2024, 1, 1)
    old = [Match(start + timedelta(days=i), "X", "A", "B", 0, 3) for i in range(40)]
    new = [Match(start + timedelta(days=600 + i), "X", "A", "B", 3, 0) for i in range(40)]
    model = DixonColesModel(ModelConfig(half_life_days=60.0, ridge=0.0,
                                        max_history_days=0)).fit(old + new)
    assert model.rating("A").net > model.rating("B").net


def test_rho_correction_changes_only_the_low_score_cells():
    plain = score_matrix_from_rates(1.4, 1.2, 0.0)
    adjusted = score_matrix_from_rates(1.4, 1.2, -0.10)
    # Both remain distributions.
    assert adjusted.sum() == pytest.approx(1.0)
    # The four corrected cells move; a high-score cell keeps its relative shape.
    assert adjusted[0, 0] != pytest.approx(plain[0, 0], abs=1e-6)
    assert adjusted[1, 1] != pytest.approx(plain[1, 1], abs=1e-6)
    ratio_high = adjusted[4, 3] / plain[4, 3]
    ratio_other = adjusted[3, 4] / plain[3, 4]
    assert ratio_high == pytest.approx(ratio_other, abs=1e-9)


def test_expected_goals_match_the_matrix_mean_when_rho_is_zero():
    lam, mu = 1.7, 1.05
    matrix = score_matrix_from_rates(lam, mu, 0.0, max_goals=14)
    goals = np.arange(matrix.shape[0])
    assert float((matrix.sum(axis=1) * goals).sum()) == pytest.approx(lam, abs=1e-4)
    assert float((matrix.sum(axis=0) * goals).sum()) == pytest.approx(mu, abs=1e-4)


def test_fitting_with_no_matches_is_an_error():
    with pytest.raises(ValueError):
        DixonColesModel().fit([])
